import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { z } from 'zod';
import { schemas } from '../apps/api/src/domain';
const paths: Record<string, unknown> = {};
const components: Record<string, unknown> = {};
for (const [name, schema] of Object.entries(schemas)) {
  const model = name[0].toUpperCase() + name.slice(1) + 'Input';
  components[model] = z.toJSONSchema(schema);
  paths[`/${name}`] = {
    get: {
      summary: `List authorized ${name}`,
      security: [{ session: [] }],
      parameters: ['q', 'status', 'page', 'limit'].map((name) => ({
        in: 'query',
        name,
        schema: { type: 'string' },
      })),
      responses: {
        200: { description: 'Scoped paginated records' },
        401: { description: 'Session required' },
        403: { description: 'Role forbidden' },
      },
    },
    post: {
      summary: `Create ${name}`,
      security: [{ session: [] }],
      parameters: [
        { in: 'header', name: 'X-CSRF-Token', required: true, schema: { type: 'string' } },
      ],
      requestBody: {
        required: true,
        content: { 'application/json': { schema: { $ref: `#/components/schemas/${model}` } } },
      },
      responses: {
        201: { description: 'Created record' },
        422: { description: 'Validation error' },
        403: { description: 'Forbidden' },
      },
    },
  };
}
paths['/{resource}/{id}/{action}'] = {
  post: {
    summary: 'Version-checked domain action. See docs/api.md for action names and payloads.',
    security: [{ session: [] }],
    parameters: [
      ...['resource', 'id', 'action'].map((name) => ({
        in: 'path',
        name,
        required: true,
        schema: { type: 'string' },
      })),
      { in: 'header', name: 'X-CSRF-Token', required: true, schema: { type: 'string' } },
      {
        in: 'header',
        name: 'Idempotency-Key',
        schema: { type: 'string' },
        description: 'Required for enrolment, payment and refund approval',
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            additionalProperties: false,
            required: ['version'],
            properties: {
              version: { type: 'integer', minimum: 1 },
              reason: { type: 'string' },
              data: {},
            },
          },
        },
      },
    },
    responses: {
      201: { description: 'Updated record' },
      409: { description: 'Version, state, capacity or idempotency conflict' },
      403: { description: 'Forbidden' },
      422: { description: 'Invalid request' },
    },
  },
};
const spec = {
  openapi: '3.1.0',
  info: {
    title: 'Medora academic API',
    version: '0.1.0',
    description:
      'Development contract. Domain creation inputs generated from runtime Zod schemas. Learning, identity and action-specific contracts remain documented separately.',
  },
  servers: [{ url: '/api/v1' }],
  paths,
  components: {
    securitySchemes: { session: { type: 'apiKey', in: 'cookie', name: 'medora_session' } },
    schemas: components,
  },
};
function typeOf(schema: any): string {
  if (schema.enum) return schema.enum.map((v: unknown) => JSON.stringify(v)).join(' | ');
  if (schema.anyOf) return schema.anyOf.map(typeOf).join(' | ');
  if (Array.isArray(schema.type))
    return schema.type.map((type: string) => typeOf({ ...schema, type })).join(' | ');
  if (schema.type === 'string') return 'string';
  if (schema.type === 'integer' || schema.type === 'number') return 'number';
  if (schema.type === 'boolean') return 'boolean';
  if (schema.type === 'null') return 'null';
  if (schema.type === 'array') return `Array<${typeOf(schema.items)}>`;
  if (schema.type === 'object') {
    if (!schema.properties) return 'Record<string, unknown>';
    return (
      '{ ' +
      Object.entries(schema.properties)
        .map(
          ([k, v]) =>
            `${JSON.stringify(k)}${schema.required?.includes(k) ? '' : '?'}: ${typeOf(v)};`,
        )
        .join(' ') +
      ' }'
    );
  }
  return 'unknown';
}
const types =
  '// Generated by scripts/contracts.ts. Do not edit.\n' +
  Object.entries(components)
    .map(([name, schema]) => `export type ${name} = ${typeOf(schema)};`)
    .join('\n') +
  '\nexport type ApiErrorEnvelope = { error: {code:string;message:string;correlation_id?:string} };\n';
mkdirSync('packages/contracts', { recursive: true });
const files = {
  'packages/contracts/openapi.json': JSON.stringify(spec, null, 2) + '\n',
  'packages/contracts/types.ts': types,
};
for (const [path, content] of Object.entries(files)) {
  if (process.argv.includes('--check')) {
    if (readFileSync(path, 'utf8') !== content) throw new Error(`Contract drift: ${path}`);
  } else writeFileSync(path, content);
}
console.log('Contracts ' + (process.argv.includes('--check') ? 'match' : 'generated'));
